SELECT INFO.REST_ID, INFO.REST_NAME, INFO.FOOD_TYPE, INFO.FAVORITES, INFO.ADDRESS,
(
    SELECT ROUND(AVG(R2.REVIEW_SCORE), 2)
    FROM REST_REVIEW R2
    WHERE R2.REST_ID = REVIEW.REST_ID
    GROUP BY R2.REST_ID
) AS SCORE
FROM REST_INFO INFO
INNER JOIN REST_REVIEW REVIEW
ON INFO.REST_ID = REVIEW.REST_ID
WHERE INFO.ADDRESS LIKE '서울%'
GROUP BY INFO.REST_ID
ORDER BY SCORE DESC, INFO.FAVORITES DESC;